name: Spotsat Webapp CI/CD Workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-with-docker:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAME: ${{ steps.build-variables.outputs.IMAGE_NAME }}
      IMAGE_VERSION: ${{ steps.build-variables.outputs.IMAGE_VERSION }}
      IMAGE_TAG: ${{ steps.build-variables.outputs.IMAGE_TAG }}
    steps:
    - name: Application Repository Checkout
      uses: actions/checkout@v4
      id: application-build 
      with:
        repository: viniciusmpacheco/spotsat-test-web-application
        ref: 'develop'

    - name: Set Build Variables
      id: build-variables
      run: |
        export IMAGE_NAME=$(jq -r '.name' package.json)
        export IMAGE_VERSION=$(jq -r '.version' package.json)
        export IMAGE_TAG=${{vars.REGISTRY_URL}}/${{vars.REGISTRY_REPOSITORY}}/${IMAGE_NAME}:${IMAGE_VERSION}

        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
        echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_OUTPUT
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

    - name: Build and Delivery Application
      id: build-delivery-application
      run: |
        docker build -t ${{steps.build-variables.outputs.IMAGE_TAG}} .
        docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
        docker push ${{steps.build-variables.outputs.IMAGE_TAG}}
    
  deploy-on-amplify:
    runs-on: ubuntu-latest
    needs: build-with-docker
    steps:

    - name: Infrastructure Repository Checkout
      uses: actions/checkout@v4
      with:
        repository: viniciusmpacheco/spotsat-test-infrastructure
        ref: 'develop'
        clean: false

    - name: Deploy Application on AWS Amplify
      run: |
        cd modules/application-amplify
        terraform init
        terraform apply -var aws_access_key=${{secrets.TF_VAR_AWS_ACCESS_KEY}} -var aws_secret_key=${{secrets.TF_VAR_AWS_SECRET_KEY}} -var github_access_token=${{secrets.TF_VAR_GITHUB_ACCESS_TOKEN}} --auto-approve
  
  deploy-on-ecs:
    runs-on: ubuntu-latest
    needs: build-with-docker
    steps:

    - name: Infrastructure Repository Checkout
      uses: actions/checkout@v4
      with:
        repository: viniciusmpacheco/spotsat-test-infrastructure
        ref: 'develop'
        clean: false
    
    - name: ver outputs
      run: cat $GITHUB_OUTPUT

    - name: ver env vars
      run: cat $GITHUB_ENV
    
    - name: ver vars
      run: env

    - name: Deploy Application on AWS ECS
      run: |
        cd modules/application-ecs
        terraform init
        terraform apply -var image_registry_url=${{vars.REGISTRY_URL}}/${{vars.REGISTRY_REPOSITORY}} -var image_name=${{needs.build-with-docker.outputs.IMAGE_NAME}} -var image_version=${{needs.build-with-docker.outputs.IMAGE_VERSION}} -var aws_access_key=${{secrets.TF_VAR_AWS_ACCESS_KEY}} -var aws_secret_key=${{secrets.TF_VAR_AWS_SECRET_KEY}} --auto-approve

